### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by j-der** [twg/accessibility#1]
README has a link for [Level A Web Content Accessibility Guidelines 2.0 (WCAG)](http://www.w3.org/WAI/WCAG20/quickref/Overview.php) that is out of date (404 response)

Suggested replacement (https://www.w3.org/WAI/WCAG20/quickref/). Filters are available to sort by Level A, AA, AAA, among others.

**Comment by ngojenny** [comment]
Thanks Jas, this has been updated!
